spring:
  profiles:
    active: dev
  application:
    name: jacksonoj-question-service
  # 配置 Spring MVC 中的路径匹配策略，支持通配符匹配
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 配置
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jackson_oj
    username: root
    password: jjw000000
  # Redis 配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  address: 0.0.0.0
  port: 8202
  servlet:
    context-path: /jacksonoj/question
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /jacksonoj

mybatis-plus:
  configuration:
    # 不开启下划线命名转驼峰
    map-underscore-to-camel-case: false
    # 将日志输出到标准输出，可以看到 sql 的执行过程
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 启动 knife4j
knife4j:
  enable: true